import Champions from '@/components/champions'
import Head from 'next/head'

import { Roboto } from "next/font/google"
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
})

type Champions = {
  champions: {
    name: string
    sprite: string
  }[]
}

export default function Home({champions}: Champions) {
  return (
    <>
      <Head>
        <title>league of nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={roboto.className}>
        <Champions champions={champions} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const response = await fetch(`${process.env.BASE_URL}/api/champions/sprites`)
  return {
    props: {
      champions: await response.json()
    }
  }
}
