import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Sprite from '@/components/sprite'

export default function Home() {
  return (
    <>
      <Head>
        <title>league of nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>This is a header</header>
      <main>
        <Sprite />
      </main>
      <footer>This is a footer</footer>
    </>
  )
}
